# Generated by Django 5.1.3 on 2024-11-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reff_no_api', '0002_userstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
