# Generated by Django 5.1.3 on 2024-11-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reff_no_api', '0003_customuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstructure',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
