# Generated by Django 5.1.3 on 2024-11-07 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reff_no_api', '0004_alter_userstructure_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstructure',
            name='ref_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
