# Generated by Django 5.1.3 on 2024-11-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reff_no_api', '0005_userstructure_ref_by_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
