# Generated by Django 5.1.3 on 2024-11-26 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reff_no_api', '0007_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstructure',
            name='ref_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ref_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
